@baseUrl = http://localhost:3000

### 0.0 Login successful
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "password123"
}
> {% client.global.set("userToken", response.body.token) %}

### 1.1 Successful creation task
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: {{userToken}}

{
  "title": "Faire les courses",
  "content": "Acheter du lait, du pain et des œufs"
}

### 1.2 Missing title (400 Bad Request)
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "content": "Acheter du lait, du pain et des œufs"
}

### 1.3 Missing content (400 Bad Request)
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Faire les courses"
}

### 1.4 Empty body (400 Bad Request)
POST {{baseUrl}}/tasks
Content-Type: application/json

{}

### 1.5 Get all tasks (should return 200 OK)
GET {{baseUrl}}/tasks/
Content-Type: application/json
Authorization: {{userToken}}
